# Generated by Django 5.2.4 on 2025-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ngo', 'NGO'), ('restaurant', 'Restaurant'), ('volunteer', 'Volunteer'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
