# Generated by Django 5.2.4 on 2025-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_donationimage_delete_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
