# Generated by Django 5.2.4 on 2025-09-11 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='donor_avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='food',
            name='donor_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='source',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('volunteer', 'Volunteer'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='NGORequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_needed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
