# Generated by Django 5.2.4 on 2025-09-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_food_available_until_food_donor_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='available_until',
        ),
        migrations.RemoveField(
            model_name='food',
            name='donor_avatar',
        ),
        migrations.RemoveField(
            model_name='food',
            name='donor_username',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='food',
            name='source',
        ),
        migrations.AlterField(
            model_name='food',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='NGORequest',
        ),
    ]
