# Generated by Django 5.2.4 on 2025-10-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='avatar1.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ngo', 'NGO'), ('restaurant', 'Restaurant'), ('volunteer', 'Volunteer'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
